flowchart LR
  classDef Contract          stroke: #00F, stroke-dasharray: 5
  classDef ApplicationModule stroke: #0F0, stroke-dasharray: 5
  classDef InferenceModality stroke: #F00, stroke-dasharray: 5

  subgraph BrowserApplication[Browser Application]
    subgraph BrowserApplication_WebPage[Web Page]
      subgraph BrowserApplication_WebPage_TextToImage[Text-To-Image]
        subgraph BrowserApplication_WebPage_TextToImage_PipelineConfigSection[Pipeline Config Section]
          BrowserApplication_WebPage_TextToImage_PipelineConfigSection_SDXL[SDXL]
          BrowserApplication_WebPage_TextToImage_PipelineConfigSection_Flux[Flux]
        end
        class BrowserApplication_WebPage_TextToImage_PipelineConfigSection ApplicationModule
      end
      class BrowserApplication_WebPage_TextToImage InferenceModality

      BrowserApplication_WebPage_MultiModal[Multi-Modal]
      class BrowserApplication_WebPage_MultiModal InferenceModality

      subgraph BrowserApplication_WebPage_TextToText[Text-To-Text]
        BrowserApplication_WebPage_TextToText_Chat[Chat]
      end
      class BrowserApplication_WebPage_TextToText InferenceModality


      BrowserApplication_WebPage_TextToImage_PipelineConfigSection_SDXL --> BrowserApplication_WebPage_Adapter_TextToImage_SDXL_ShortfinV1
      BrowserApplication_WebPage_TextToImage_PipelineConfigSection_Flux --> BrowserApplication_WebPage_Adapter_TextToImage_Flux_ShortfinV1

      BrowserApplication_WebPage_MultiModal BrowserApplication_WebPage__MultiModal__BrowserApplication_WebPage_Adapter@--> BrowserApplication_WebPage_Adapter_MultiModal
      class BrowserApplication_WebPage__MultiModal__BrowserApplication_WebPage_Adapter InferenceModality

      BrowserApplication_WebPage_TextToText_Chat                        --> BrowserApplication_WebPage_Adapter_TextToText_Chat_ShortfinV1


      subgraph BrowserApplication_WebPage_Adapter[Adapter]
        subgraph BrowserApplication_WebPage_Adapter_TextToImage[Text-To-Image]
          BrowserApplication_WebPage_Adapter_TextToImage_SDXL_ShortfinV1[SDXL <-> Shortfin v1]
          BrowserApplication_WebPage_Adapter_TextToImage_Flux_ShortfinV1[Flux <-> Shortfin v1]
        end
        class BrowserApplication_WebPage_Adapter_TextToImage InferenceModality


        BrowserApplication_WebPage_Adapter_MultiModal[Multi-Modal]
        class BrowserApplication_WebPage_Adapter_MultiModal InferenceModality


        subgraph BrowserApplication_WebPage_Adapter_TextToText[Text-To-Text]
          BrowserApplication_WebPage_Adapter_TextToText_Chat_ShortfinV1[Chat <-> Shortfin v1]
        end
        class BrowserApplication_WebPage_Adapter_TextToText InferenceModality

        BrowserApplication_WebPage_Adapter_TextToImage_SDXL_ShortfinV1 --> BrowserApplication_WebPage_Adapter_Junction_ShortfinV1
        BrowserApplication_WebPage_Adapter_TextToImage_Flux_ShortfinV1 --> BrowserApplication_WebPage_Adapter_Junction_ShortfinV1
        BrowserApplication_WebPage_Adapter_TextToText_Chat_ShortfinV1  --> BrowserApplication_WebPage_Adapter_Junction_ShortfinV1

        BrowserApplication_WebPage_Adapter_Junction_ShortfinV1@{ shape: f-circ }
      end
      class BrowserApplication_WebPage_Adapter ApplicationModule
    end
    class BrowserApplication_WebPage ApplicationModule


    BrowserApplication_WebPage_Adapter_TextToImage BrowserApplication_WebPage_Adapter__TextToImage__BrowserApplication_WebServiceSDK_API@---> BrowserApplication_WebServiceSDK_API_TextToImage
    class BrowserApplication_WebPage_Adapter_TextToImage InferenceModality
    class BrowserApplication_WebPage_Adapter__TextToImage__BrowserApplication_WebServiceSDK_API InferenceModality


    BrowserApplication_WebPage_Adapter_MultiModal BrowserApplication_WebPage_Adapter__MultiModal__BrowserApplication_WebServiceSDK_API@---> BrowserApplication_WebServiceSDK_API_MultiModal
    class BrowserApplication_WebPage_Adapter__MultiModal__BrowserApplication_WebServiceSDK_API InferenceModality


    BrowserApplication_WebPage_Adapter_Junction_ShortfinV1 --> BrowserApplication_WebServiceSDK_API_MultiModal_Shortfin_v1

    BrowserApplication_WebPage_Adapter_TextToText BrowserApplication_WebPage_Adapter__TextToText__BrowserApplication_WebServiceSDK_API@---> BrowserApplication_WebServiceSDK_API_TextToText
    class BrowserApplication_WebPage_Adapter_TextToText InferenceModality
    class BrowserApplication_WebPage_Adapter__TextToText__BrowserApplication_WebServiceSDK_API InferenceModality


    subgraph BrowserApplication_WebServiceSDK_API[Web Service SDK API]
      BrowserApplication_WebServiceSDK_API_TextToImage[Text-To-Image]
      class BrowserApplication_WebServiceSDK_API_TextToImage InferenceModality

      subgraph BrowserApplication_WebServiceSDK_API_MultiModal[Multi-Modal]
        BrowserApplication_WebServiceSDK_API_MultiModal_Shortfin_v1[Shortfin v1]
      end
      class BrowserApplication_WebServiceSDK_API_MultiModal InferenceModality

      BrowserApplication_WebServiceSDK_API_TextToText[Text-To-Text]
      class BrowserApplication_WebServiceSDK_API_TextToText InferenceModality
    end
    class BrowserApplication_WebServiceSDK_API Contract


    BrowserApplication_WebServiceSDK_API_TextToImage BrowserApplication_WebServiceSDK_API__TextToImage__BrowserApplication_WebServiceSDK@--> BrowserApplication_WebServiceSDK_TextToImage
    class BrowserApplication_WebServiceSDK_API__TextToImage__BrowserApplication_WebServiceSDK InferenceModality

    BrowserApplication_WebServiceSDK_API_MultiModal_Shortfin_v1 --> BrowserApplication_WebServiceSDK_MultiModal_Shortfin_v1

    BrowserApplication_WebServiceSDK_API_TextToText BrowserApplication_WebServiceSDK_API__TextToText__BrowserApplication_WebServiceSDK@--> BrowserApplication_WebServiceSDK_TextToText
    class BrowserApplication_WebServiceSDK_API__TextToText__BrowserApplication_WebServiceSDK InferenceModality


    subgraph BrowserApplication_WebServiceSDK[Web Service SDK]
      subgraph BrowserApplication_WebServiceSDK_TextToImage[Text-To-Image]
        BrowserApplication_WebServiceSDK_TextToImage_StabilityAI[Stability AI]
        BrowserApplication_WebServiceSDK_TextToImage_Shortfin_v0[Shortfin v0]
        BrowserApplication_WebServiceSDK_TextToImage_BlackForestLabs[Black Forest Labs]
      end
      class BrowserApplication_WebServiceSDK_TextToImage InferenceModality

      subgraph BrowserApplication_WebServiceSDK_MultiModal[Multi-Modal]
        BrowserApplication_WebServiceSDK_MultiModal_OpenAI[OpenAI]
        BrowserApplication_WebServiceSDK_MultiModal_Shortfin_v1[Shortfin v1]
      end
      class BrowserApplication_WebServiceSDK_MultiModal InferenceModality

      subgraph BrowserApplication_WebServiceSDK_TextToText[Text-To-Text]
        BrowserApplication_WebServiceSDK_TextToText_Shortfin_v0_LLM[Shortfin v0 for LLM]
      end
      class BrowserApplication_WebServiceSDK_TextToText InferenceModality
    end
    class BrowserApplication_WebServiceSDK ApplicationModule
  end


  BrowserApplication_WebServiceSDK_TextToImage_StabilityAI     --> WebAPI_TextToImage_StabilityAI
  BrowserApplication_WebServiceSDK_TextToImage_Shortfin_v0     --> WebAPI_TextToImage_Shortfin_v0_SDXL
  BrowserApplication_WebServiceSDK_TextToImage_Shortfin_v0     --> WebAPI_TextToImage_Shortfin_v0_Flux
  BrowserApplication_WebServiceSDK_TextToImage_BlackForestLabs --> WebAPI_TextToImage_BlackForestLabs

  BrowserApplication_WebServiceSDK_MultiModal_OpenAI           --> WebAPI_MultiModal_OpenAI
  BrowserApplication_WebServiceSDK_MultiModal_Shortfin_v1      --> WebAPI_MultiModal_Shortfin_v1

  BrowserApplication_WebServiceSDK_TextToText_Shortfin_v0_LLM  --> WebAPI_TextToText_Shortfin_v0_LLM


  subgraph WebAPI[Web API]
    subgraph WebAPI_TextToImage[Text-To-Image]
      WebAPI_TextToImage_StabilityAI[Stability AI]
      WebAPI_TextToImage_Shortfin_v0_SDXL[Shortfin v0 for SDXL]
      WebAPI_TextToImage_Shortfin_v0_Flux[Shortfin v0 for Flux]
      WebAPI_TextToImage_BlackForestLabs[Black Forest Labs]
    end
    class WebAPI_TextToImage InferenceModality

    subgraph WebAPI_MultiModal[Multi-Modal]
      WebAPI_MultiModal_OpenAI[OpenAI]
      WebAPI_MultiModal_Shortfin_v1[Shortfin v1]
    end
    class WebAPI_MultiModal InferenceModality

    subgraph WebAPI_TextToText[Text-To-Text]
      WebAPI_TextToText_Shortfin_v0_LLM[Shortfin v0 for LLM]
    end
    class WebAPI_TextToText InferenceModality
  end
  class WebAPI Contract


  WebAPI_TextToImage_StabilityAI      --> RemoteApplication_WebService_TextToImage_StabilityAI
  WebAPI_TextToImage_Shortfin_v0_SDXL --> RemoteApplication_WebService_TextToImage_Shortfin_v0_SDXL
  WebAPI_TextToImage_Shortfin_v0_Flux --> RemoteApplication_WebService_TextToImage_Shortfin_v0_Flux
  WebAPI_TextToImage_BlackForestLabs  --> RemoteApplication_WebService_TextToImage_BlackForestLabs

  WebAPI_MultiModal_OpenAI            --> RemoteApplication_WebService_MultiModal_OpenAI
  WebAPI_MultiModal_Shortfin_v1       --> RemoteApplication_WebService_MultiModal_Shortfin_v1

  WebAPI_TextToText_Shortfin_v0_LLM   --> RemoteApplication_WebService_TextToText_Shortfin_v0_LLM


  subgraph RemoteApplication[Remote Application]
    subgraph RemoteApplication_WebService[Web Service]
      subgraph RemoteApplication_WebService_TextToImage[Text-To-Image]
        RemoteApplication_WebService_TextToImage_StabilityAI[Stability AI]
        RemoteApplication_WebService_TextToImage_Shortfin_v0_SDXL[Shortfin v0 for SDXL]
        RemoteApplication_WebService_TextToImage_Shortfin_v0_Flux[Shortfin v0 for Flux]
        RemoteApplication_WebService_TextToImage_BlackForestLabs[Black Forest Labs]
      end
      class RemoteApplication_WebService_TextToImage InferenceModality

      subgraph RemoteApplication_WebService_MultiModal[Multi-Modal]
        RemoteApplication_WebService_MultiModal_OpenAI[OpenAI]
        RemoteApplication_WebService_MultiModal_Shortfin_v1[Shortfin v1]
      end
      class RemoteApplication_WebService_MultiModal InferenceModality

      subgraph RemoteApplication_WebService_TextToText[Text-To-Text]
        RemoteApplication_WebService_TextToText_Shortfin_v0_LLM[Shortfin v0 for LLM]
      end
      class RemoteApplication_WebService_TextToText InferenceModality

      RemoteApplication_WebService_TextToImage_StabilityAI     ---> RemoteApplication_WebService_Adapter_TextToImage_StabilityAI
      RemoteApplication_WebService_TextToImage_BlackForestLabs ---> RemoteApplication_WebService_Adapter_TextToImage_BlackForestLabs

      RemoteApplication_WebService_MultiModal_OpenAI            --> RemoteApplication_WebService_Adapter_MultiModal_OpenAI_Junction_Native
      RemoteApplication_WebService_MultiModal_Shortfin_v1       --> RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_Junction

      RemoteApplication_WebService_TextToText_Shortfin_v0_LLM  ---- RemoteApplication_WebService_Adapter_TextToText_Shortfin_v0_LLM_Skip

      subgraph RemoteApplication_WebService_Adapter[Adapter]
        subgraph RemoteApplication_WebService_Adapter_TextToImage[Text-To-Image]
          RemoteApplication_WebService_Adapter_TextToImage_StabilityAI[Stability AI <-> Shortfin v0 SDXL]
          RemoteApplication_WebService_Adapter_TextToImage_BlackForestLabs[Black Forest Labs <-> Shortfin v0 Flux]

          RemoteApplication_WebService_Adapter_TextToImage_StabilityAI     --> RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_SDXL_Skip
          RemoteApplication_WebService_TextToImage_Shortfin_v0_SDXL        --> RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_SDXL_Skip
          RemoteApplication_WebService_TextToImage_Shortfin_v0_Flux        --> RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_Flux_Skip
          RemoteApplication_WebService_Adapter_TextToImage_BlackForestLabs --> RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_Flux_Skip

          RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_SDXL_Skip@{ shape: f-circ }
          RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_Flux_Skip@{ shape: f-circ }
        end
        class RemoteApplication_WebService_Adapter_TextToImage InferenceModality


        subgraph RemoteApplication_WebService_Adapter_MultiModal[Multi-Modal]
          subgraph RemoteApplication_WebService_Adapter_MultiModal_OpenAI[OpenAI]
            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_Junction_Native@{ shape: f-circ }

            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_Junction_Native --> RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0SDXL
            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_Junction_Native --> RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0Flux
            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_Junction_Native --> RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0LLM

            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0SDXL[Shortfin v0 SDXL]
            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0Flux[Shortfin v0 Flux]
            RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0LLM[Shortfin v0 LLM]
          end
          class RemoteApplication_WebService_Adapter_MultiModal_OpenAI ApplicationModule

          subgraph RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1[Shortfin v1]
            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_Junction@{ shape: f-circ }

            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_Junction --> RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0SDXL
            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_Junction --> RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0Flux
            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_Junction --> RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0LLM

            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0SDXL[Shortfin v0 for SDXL]
            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0Flux[Shortfin v0 for Flux]
            RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0LLM[Shortfin v0 for LLM]
          end
          class RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1 ApplicationModule

          RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0SDXL     --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0SDXL
          RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0Flux     --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0Flux
          RemoteApplication_WebService_Adapter_MultiModal_OpenAI_ShortfinV0LLM      --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0LLM
          RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0SDXL --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0SDXL
          RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0Flux --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0Flux
          RemoteApplication_WebService_Adapter_MultiModal_ShortfinV1_ShortfinV0LLM  --> RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0LLM

          RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0SDXL@{ shape: f-circ }
          RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0Flux@{ shape: f-circ }
          RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0LLM@{ shape: f-circ }
        end
        class RemoteApplication_WebService_Adapter_MultiModal InferenceModality


        subgraph RemoteApplication_WebService_Adapter_TextToText[Text-To-Text]
          RemoteApplication_WebService_Adapter_TextToText_Shortfin_v0_LLM_Skip@{ shape: f-circ }
        end
        class RemoteApplication_WebService_Adapter_TextToText InferenceModality


        RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_SDXL_Skip  --> RemoteApplication_WebService_Adapter_Junction_v0_SDXL
        RemoteApplication_WebService_Adapter_TextToImage_Shortfin_v0_Flux_Skip  --> RemoteApplication_WebService_Adapter_Junction_v0_Flux
        RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0SDXL --> RemoteApplication_WebService_Adapter_Junction_v0_SDXL
        RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0Flux --> RemoteApplication_WebService_Adapter_Junction_v0_Flux
        RemoteApplication_WebService_Adapter_MultiModal_Junction_ShortfinV0LLM  --> RemoteApplication_WebService_Adapter_Junction_v0_LLM
        RemoteApplication_WebService_Adapter_TextToText_Shortfin_v0_LLM_Skip   ---> RemoteApplication_WebService_Adapter_Junction_v0_LLM

        RemoteApplication_WebService_Adapter_Junction_v0_SDXL@{ shape: f-circ }
        RemoteApplication_WebService_Adapter_Junction_v0_Flux@{ shape: f-circ }
        RemoteApplication_WebService_Adapter_Junction_v0_LLM@{ shape: f-circ }
      end
      class RemoteApplication_WebService_Adapter ApplicationModule
    end
    class RemoteApplication_WebService ApplicationModule


    RemoteApplication_WebService_Adapter_Junction_v0_SDXL --> RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_SDXL
    RemoteApplication_WebService_Adapter_Junction_v0_Flux --> RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_Flux

    RemoteApplication_WebService_Adapter_MultiModal RemoteApplication_WebService_Adapter__MultiModal__RemoteApplication_InferencePipeline_API@--> RemoteApplication_InferencePipeline_API_MultiModal
    class RemoteApplication_WebService_Adapter_MultiModal InferenceModality
    class RemoteApplication_WebService_Adapter__MultiModal__RemoteApplication_InferencePipeline_API InferenceModality

    RemoteApplication_WebService_Adapter_Junction_v0_LLM  --> RemoteApplication_InferencePipeline_API_TextToText_Shortfin_v0_LLM


    subgraph RemoteApplication_InferencePipeline_API[Inference Pipeline API]
      subgraph RemoteApplication_InferencePipeline_API_TextToImage[Text-To-Image]
        RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_SDXL[Shortfin v0 for SDXL]
        RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_Flux[Shortfin v0 for Flux]
      end
      class RemoteApplication_InferencePipeline_API_TextToImage InferenceModality

      RemoteApplication_InferencePipeline_API_MultiModal[Multi-Modal]
      class RemoteApplication_InferencePipeline_API_MultiModal InferenceModality

      subgraph RemoteApplication_InferencePipeline_API_TextToText[Text-To-Text]
        RemoteApplication_InferencePipeline_API_TextToText_Shortfin_v0_LLM[Shortfin v0 for LLM]
      end
      class RemoteApplication_InferencePipeline_API_TextToText InferenceModality
    end
    class RemoteApplication_InferencePipeline_API Contract


    RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_SDXL ---> RemoteApplication_InferencePipeline_TextToImage_SDXL
    RemoteApplication_InferencePipeline_API_TextToImage_Shortfin_v0_Flux ---> RemoteApplication_InferencePipeline_TextToImage_Flux

    RemoteApplication_InferencePipeline_API_MultiModal RemoteApplication_InferencePipeline_API__MultiModal__RemoteApplication_InferencePipeline@---> RemoteApplication_InferencePipeline_MultiModal
    class RemoteApplication_InferencePipeline_API__MultiModal__RemoteApplication_InferencePipeline InferenceModality

    RemoteApplication_InferencePipeline_API_TextToText_Shortfin_v0_LLM    --> RemoteApplication_InferencePipeline_TextToText_Junction_v0


    subgraph RemoteApplication_InferencePipeline[Inference Pipeline]
      subgraph RemoteApplication_InferencePipeline_TextToText[Text-To-Text]
        RemoteApplication_InferencePipeline_TextToText_Junction_v0@{ shape: f-circ }

        RemoteApplication_InferencePipeline_TextToText_Junction_v0 --> RemoteApplication_InferencePipeline_TextToText_Llama
        RemoteApplication_InferencePipeline_TextToText_Junction_v0 --> RemoteApplication_InferencePipeline_TextToText_DeepSeek

        RemoteApplication_InferencePipeline_TextToText_Llama[v0 Llama]
        RemoteApplication_InferencePipeline_TextToText_DeepSeek[v0 DeepSeek]
      end
      class RemoteApplication_InferencePipeline_TextToText InferenceModality

      subgraph RemoteApplication_InferencePipeline_MultiModal[Multi-Modal]
        RemoteApplication_InferencePipeline_MultiModal_Unknown[?]
      end
      class RemoteApplication_InferencePipeline_MultiModal InferenceModality

      subgraph RemoteApplication_InferencePipeline_TextToImage[Text-To-Image]
        RemoteApplication_InferencePipeline_TextToImage_SDXL[v0 SDXL]
        RemoteApplication_InferencePipeline_TextToImage_Flux[v0 Flux]
      end
      class RemoteApplication_InferencePipeline_TextToImage InferenceModality
    end
    class RemoteApplication_InferencePipeline ApplicationModule
  end
