flowchart LR
  classDef Contract          stroke: #00F, stroke-dasharray: 5
  classDef ApplicationModule stroke: #0F0, stroke-dasharray: 5

  subgraph BrowserApplication[Browser Application]
    BrowserApplication_WebPage[Web Page]
    class BrowserApplication_WebPage ApplicationModule

    BrowserApplication_WebPage --> BrowserApplication_WebServiceSDK_API

    BrowserApplication_WebServiceSDK_API[Web Service SDK API]
    class BrowserApplication_WebServiceSDK_API Contract

    BrowserApplication_WebServiceSDK_API --> BrowserApplication_WebServiceSDK

    BrowserApplication_WebServiceSDK[Web Service SDK]
    class BrowserApplication_WebServiceSDK ApplicationModule
  end

  BrowserApplication_WebServiceSDK --> WebAPI

  WebAPI[Web API]
  class WebAPI Contract

  WebAPI --> RemoteApplication_WebService

  subgraph RemoteApplication[Remote Application]
    RemoteApplication_WebService[Web Service]
    class RemoteApplication_WebService ApplicationModule

    RemoteApplication_WebService --> RemoteApplication_InferencePipeline_API

    RemoteApplication_InferencePipeline_API[Inference Pipeline API]
    class RemoteApplication_InferencePipeline_API Contract

    RemoteApplication_InferencePipeline_API --> RemoteApplication_InferencePipeline

    RemoteApplication_InferencePipeline[Inference Pipeline]
    class RemoteApplication_InferencePipeline ApplicationModule
  end
