flowchart LR
  classDef Contract          stroke: #00F, stroke-dasharray: 5
  classDef ApplicationModule stroke: #0F0, stroke-dasharray: 5

  subgraph BrowserApplication[Browser Application]
    BrowserApplication_WebPage[Web Page]
    class BrowserApplication_WebPage ApplicationModule

    BrowserApplication_WebServiceSDK[Web Service SDK]
    class BrowserApplication_WebServiceSDK ApplicationModule
  end

  BrowserApplication_WebServiceSDK --> WebAPI

  WebAPI[Web API]
  class WebAPI Contract

  WebAPI --> RemoteApplication_WebService

  subgraph RemoteApplication[Remote Application]
    RemoteApplication_WebService[Web Service]
    class RemoteApplication_WebService ApplicationModule

    RemoteApplication_DomainSpecificJob[Domain-Specific Job]
    class RemoteApplication_DomainSpecificJob ApplicationModule
  end
